version = 1

# Debian build scripts
[[annotations]]
path = "debian/arduino-router/**"
SPDX-FileCopyrightText = "Arduino s.r.l. and/or its affiliated companies"
SPDX-License-Identifier = "GPL-3.0-or-later"

# Tool-generated or configuration files.
[[annotations]]
path = [
  ".dockerignore",
  ".editorconfig",
  ".golangci.yml",
  ".gitignore",
  ".licensed.yml",
  ".licenses/**",
  "dprint.json",
  "go.mod",
  "go.sum",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
