version = 1

# Tool-generated or configuration files.
[[annotations]]
path = [
  ".dockerignore",
  ".editorconfig",
  ".golangci.yml",
  ".gitignore",
  ".github/**",
  ".licensed.yml",
  ".licenses/**",
  "dprint.json",
  "go.mod",
  "go.sum",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
