name: Check REUSE Compliance

on:
  create:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:

jobs:
  run-reuse-linter:
    name: Run REUSE linter
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Install tools
        run: |
          go tool \
            github.com/go-task/task/v3/cmd/task \
              --silent \
              init

      - name: Check REUSE compliance
        run: |
          go tool \
            github.com/go-task/task/v3/cmd/task \
              --silent \
              lint:reuse >> $GITHUB_STEP_SUMMARY
